runtime: python313
service: api
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  INSTANCE_CONNECTION_NAME: "prestij-nurazwann-smartassist:asia-southeast1:drespon-db"
  DB_NAME: "drespon"
  DB_USER: "drespon_user"
  SECRET_NAME: "projects/prestij-nurazwann-smartassist/secrets/drespon-db-pass/versions/latest"

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.7

vpc_access_connector:
  name: projects/prestij-nurazwann-smartassist/locations/asia-southeast1/connectors/drespon-connector
  egress_setting: private-ranges-only
